var gmail_scripts = ['gmail.js', 'gmail_executor.js'];
var gmail_scripts_urls = [];

for (var i = 0; i < gmail_scripts.length; i++) {
    gmail_scripts_urls.push(chrome.extension.getURL(gmail_scripts[i]));
}

var e2ePgpContext = new e2e.openpgp.ContextImpl();
var pass_phrase = 'qwerty';//'snlplY7EdLJJHUiy';
var uid = 'Autogenerated Key (Biomio) <test@mail.com>';
window.onload = function () {
    $('body').append('<div id="biomio_elements"></div>');
    var biomio_elems = $('#biomio_elements');
    biomio_elems.load(chrome.extension.getURL('additional_html.html'), function () {
        for (i = 0; i < gmail_scripts_urls.length; i++) {
            biomio_elems.append('<script src="' + gmail_scripts_urls[i] + '"></script>');
        }
    });
};


window.addEventListener("message", function (event) {
    if (event.data.type && (event.data.type == "test_encrypt_sign")) {
        encrypt_message(event.data.data);
    } else if (event.data.type && (event.data.type == "decrypt_message")) {
        decrypt_message(event.data.data);
    }
}, false);

e2ePgpContext.setArmorHeader('Version', 'BioMio v1.0');
e2ePgpContext.setKeyRingPassphrase(pass_phrase);

function encrypt_message(data) {
    console.log('Encrypt: ', data);
    var public_keys = e2ePgpContext.searchPublicKey([uid]);
    console.log(public_keys);
    var sender_private_key = e2ePgpContext.searchPrivateKey(uid);
    var encrypted_content = e2ePgpContext.encryptSign(data.content, [], public_keys.result_, [], sender_private_key.result_[0]);
    data.content = encrypted_content.result_;
    data.completedAction = 'encrypt_only';
    sendResponse(data);
}

function decrypt_message(data) {
    console.log('Decrypt: ', data);
    var decrypted_text = e2ePgpContext.verifyDecrypt(function (passphraseCallback) {
        passphraseCallback(pass_phrase);
    }, data.content);
    data.content = e2e.byteArrayToStringAsync(decrypted_text.result_.decrypt.data, decrypted_text.result_.decrypt.options.charset);
    data.completedAction = 'decrypt_verify';
    sendResponse(data);
}

function sendResponse(message) {
    console.log(message);
    window.postMessage(message, '*');
}